databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio

services:
  - type: web
    name: django-portfolio
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: portfolio.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
