# Generated by Django 5.2.4 on 2025-10-02 05:09

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_project_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=portfolio.models.project_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="live_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="repository_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "In Arbeit"),
                    ("completed", "Abgeschlossen"),
                    ("archived", "Archiviert"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="portfolio.technology"),
        ),
    ]
