# Generated by Django 5.2.4 on 2026-01-09 19:33

import django.db.models.deletion
import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_technology_remove_project_url_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.certificateissuer'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(upload_to=portfolio.models.certificate_pdf_upload_path, validators=[portfolio.models.validate_pdf_mimetype]),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
