# Generated by Django 5.2.4 on 2026-01-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_technology_options_alter_certificate_issuer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
